# Práctico Especial — EPA Fuel Economy, Model Year 2025

**Ejercicio 1**: Un análisis exploratorio inicial de la base, investigando con recursos online el
(posible) origen de los datos, caracterizando sus atributos y describiendo su
comportamiento, distribución de variables, presencia de outliers, valores
nulos y demás particularidades que crea de relevancia para el análisis.

Primero descargamos el dataset en caso de que no exista.

In [49]:
from wget import download
from os import path

#Descargamos el dataset en caso de que no exista
if not path.exists("25-testcar-2026-01-21.xlsx"):
    download("https://drive.google.com/file/d/1SrWg-tvyGMxnR0KNi46dlA2KIq6kku6F/view")
else:
    print("Ya existe el archivo.")

Ya existe el archivo.

In [50]:
import pandas as pd

df = pd.read_excel("25-testcar-2026-01-21.xlsx")

df

,Model Year,Vehicle Manufacturer Name,Veh Mfr Code,Represented Test Veh Make,Represented Test Veh Model,Test Vehicle ID,Test Veh Configuration #,Test Veh Displacement (L),Actual Tested Testgroup,Vehicle Type,...,Set Coef A (lbf),Set Coef B (lbf/mph),Set Coef C (lbf/mph**2),Aftertreatment Device Cd,Aftertreatment Device Desc,Police - Emergency Vehicle?,Averaging Group ID,Averaging Weighting Factor,Averaging Method Cd,Averging Method Desc
0,2025,aston martin,ASX,Aston Martin,DB12 V8,5723PT5601,0,4.000,RASXV04.0AES,Car,...,5.67,0.0083,0.0221,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
1,2025,aston martin,ASX,Aston Martin,DB12 V8,5723PT5601,0,4.000,RASXV04.0AES,Car,...,5.67,0.0083,0.0221,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
2,2025,aston martin,ASX,Aston Martin,DBX 707,8841PT8473,0,4.000,PASXJ04.0AEX,Both,...,-4.88,-0.5318,0.0367,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
3,2025,aston martin,ASX,Aston Martin,DBX 707,8841PT8473,0,4.000,PASXJ04.0AEX,Both,...,-4.88,-0.5318,0.0367,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
4,2025,aston martin,ASX,Aston Martin,Vanquish,370TT7334,0,5.200,SASXV05.2AMV,Car,...,-0.57,-0.0029,0.0128,TWC,Three-way catalyst,N,NaN,NaN,N,No averaging
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4282,2025,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,...,-8.08,-0.0412,0.0213,NaN,NaN,N,NaN,NaN,N,No averaging
4283,2025,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,...,-8.08,-0.0412,0.0213,NaN,NaN,N,NaN,NaN,N,No averaging
4284,2025,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,...,-7.96,0.0127,0.0206,NaN,NaN,N,NaN,NaN,N,No averaging
4285,2025,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,...,-8.08,-0.0412,0.0213,NaN,NaN,N,NaN,NaN,N,No averaging
4286,2025,Wuhan Lotus Cars Co,WHN,Lotus,ELETRE S Performance,GIC_C10_6119,0,0.001,SWHNV00.0LEB,Car,...,-8.08,-0.0412,0.0213,NaN,NaN,N,NaN,NaN,N,No averaging

In [51]:
print('Cantidad de filas y columnas:', df.shape)
df.head()
df.info()

Cantidad de filas y columnas: (4287, 67)
<class 'pandas.DataFrame'>
RangeIndex: 4287 entries, 0 to 4286
Data columns (total 67 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Model Year                      4287 non-null   int64
 1   Vehicle Manufacturer Name       4287 non-null   str
 2   Veh Mfr Code                    4287 non-null   str
 3   Represented Test Veh Make       4287 non-null   str
 4   Represented Test Veh Model      4287 non-null   str
 5   Test Vehicle ID                 4287 non-null   str
 6   Test Veh Configuration #        4287 non-null   int64
 7   Test Veh Displacement (L)       4287 non-null   float64
 8   Actual Tested Testgroup         4287 non-null   str
 9   Vehicle Type                    4287 non-null   str
 10  Rated Horsepower                4287 non-null   int64
 11  # of Cylinders and Rotors       3617 non-null   float64
 12  Engine Code                     4287 non-null   str
 13  Tested Transmission Type Code   4287 non-null   str
 14  Tested Transmission Type        4287 non-null   str
 15  # of Gears                      4287 non-null   int64
 16  Transmission Lockup?            4287 non-null   str
 17  Drive System Code               4287 non-null   str
 18  Drive System Description        4287 non-null   str
 19  Transmission Overdrive Code     4287 non-null   int64
 20  Transmission Overdrive Desc     4287 non-null   str
 21  Equivalent Test Weight (lbs.)   4287 non-null   int64
 22  Axle Ratio                      4287 non-null   float64
 23  N/V Ratio                       4287 non-null   float64
 24  Shift Indicator Light Use Cd    4287 non-null   int64
 25  Shift Indicator Light Use Desc  4287 non-null   str
 26  Test Number                     4287 non-null   str
 27  Test Originator                 4287 non-null   str
 28  Analytically Derived FE?        4287 non-null   str
 29  ADFE Test Number                212 non-null    str
 30  ADFE Total Road Load HP         212 non-null    float64
 31  ADFE Equiv. Test Weight (lbs.)  212 non-null    float64
 32  ADFE N/V Ratio                  212 non-null    float64
 33  Test Procedure Cd               4287 non-null   int64
 34  Test Procedure Description      4287 non-null   str
 35  Test Fuel Type Cd               4287 non-null   int64
 36  Test Fuel Type Description      4287 non-null   str
 37  Test Category                   4287 non-null   str
 38  THC (g/mi)                      3329 non-null   float64
 39  CO (g/mi)                       3403 non-null   float64
 40  CO2 (g/mi)                      3563 non-null   float64
 41  NOx (g/mi)                      3402 non-null   float64
 42  PM (g/mi)                       389 non-null    float64
 43  CH4 (g/mi)                      3165 non-null   float64
 44  N2O (g/mi)                      2224 non-null   float64
 45  RND_ADJ_FE                      4066 non-null   float64
 46  FE_UNIT                         4287 non-null   str
 47  FE Bag 1                        1864 non-null   float64
 48  FE Bag 2                        1864 non-null   float64
 49  FE Bag 3                        1453 non-null   float64
 50  FE Bag 4                        388 non-null    float64
 51  DT-Inertia Work Ratio Rating    3592 non-null   float64
 52  DT-Absolute Speed Change Ratg   3592 non-null   float64
 53  DT-Energy Economy Rating        3592 non-null   float64
 54  Target Coef A (lbf)             4287 non-null   float64
 55  Target Coef B (lbf/mph)         4287 non-null   float64
 56  Target Coef C (lbf/mph**2)      4287 non-null   float64
 57  Set Coef A (lbf)                4287 non-null   float64
 58  Set Coef B (lbf/mph)            4287 non-null   float64
 59  Set Coef C (lbf/mph**2)         4287 non-null   float64
 60  Aftertreatment Device Cd        3617 non-null   str
 61  Aftertreatment Device Desc      3617 non-null   str
 62  Police - Emergency Vehicle?     4287 non-null   str
 63  Averaging Group ID              75 non-null     str
 64  Averaging Weighting Factor      75 non-null     float64
 65  Averaging Method Cd             4287 non-null   str
 66  Averging Method Desc            4287 non-null   str
dtypes: float64(29), int64(9), str(29)
memory usage: 2.2 MB

La base contiene 4.287 filas y 67 columnas. Las filas son registros de pruebas y las columnas describen características técnicas del vehículo, información de la prueba, economía de combustible y emisiones.
Se observan identificadores de vehículos y modelos, por lo que conviene distinguir entre cantidad de registros y cantidad de vehículos/modelos únicos.

In [52]:
#Analizamos el porcentaje de nulos que posee cada variable:

porcentaje_nulos = (df.isna().sum() / len(df)) * 100
print("Top 15 columnas con más valores nulos:")
porcentaje_nulos[porcentaje_nulos > 0].sort_values(ascending=False).head(67)

Top 15 columnas con más valores nulos:

Averaging Group ID                98.250525
Averaging Weighting Factor        98.250525
ADFE Test Number                  95.054817
ADFE Total Road Load HP           95.054817
ADFE Equiv. Test Weight (lbs.)    95.054817
ADFE N/V Ratio                    95.054817
FE Bag 4                          90.949382
PM (g/mi)                         90.926056
FE Bag 3                          66.106835
FE Bag 1                          56.519711
FE Bag 2                          56.519711
N2O (g/mi)                        48.122230
CH4 (g/mi)                        26.172148
THC (g/mi)                        22.346629
NOx (g/mi)                        20.643807
CO (g/mi)                         20.620481
CO2 (g/mi)                        16.888267
DT-Absolute Speed Change Ratg     16.211803
DT-Energy Economy Rating          16.211803
DT-Inertia Work Ratio Rating      16.211803
# of Cylinders and Rotors         15.628645
Aftertreatment Device Desc        15.628645
Aftertreatment Device Cd          15.628645
RND_ADJ_FE                         5.155120
dtype: float64

Podemos observar que algunas variables poseen un porcentaje alto de valores nulos, los cuales podrian ser descartados. Las primeras 8 variables que aparecen poseen mas de un 90% de valores nulos. Las siguientes tienen entre un 15% y un 66%. Este tipo de variables se pueden analizar para ver si sus datos son relevantes.

# Consulta

In [53]:
df['Test Fuel Type Description'].value_counts()
df.groupby('Test Fuel Type Description')['RND_ADJ_FE'].agg(['count','mean','std'])

                                               count          mean         std
Test Fuel Type Description
CARB LEV3 E10 Premium Gasoline                     2  10000.000000    0.000000
CARB LEV3 E10 Regular Gasoline                     1  10000.000000         NaN
Cold CO E10 Regular Gasoline (Tier 3)              2  10000.000000    0.000000
Cold CO Premium (Tier 2)                          57    178.943860  850.031719
Cold CO Regular (Tier 2)                         160     31.813125   11.923884
E85 (85% Ethanol 15% EPA Unleaded Gasoline)       12     27.358333    8.622008
Electricity                                      563    106.251332  151.962741
Federal Cert Diesel 7-15 PPM Sulfur              150     29.902000    7.234022
Hydrogen 5                                        10     70.640000   38.498779
Tier 2 Cert Gasoline                            3106     33.324984   11.903670
Tier 3 E10 Regular Gasoline (9 RVP @Low Alt.)      3  10000.000000    0.000000

In [54]:
#Filtramos variables cualitativas y nos quedamos solo con las cuantitativas.



df.describe().T

,count,mean,std,min,25%,50%,75%,max
Model Year,4287.0,2025.000000,0.000000,2025.000000,2025.000000,2025.000000,2025.000000,2025.000000
Test Veh Configuration #,4287.0,0.908328,1.255968,0.000000,0.000000,0.000000,1.000000,8.000000
Test Veh Displacement (L),4287.0,4.688139,14.572038,0.001000,1.991000,2.487000,3.000000,99.999000
Rated Horsepower,4287.0,340.698157,175.121581,1.000000,201.000000,305.000000,409.000000,1948.000000
# of Cylinders and Rotors,3617.0,5.222007,1.624339,3.000000,4.000000,4.000000,6.000000,16.000000
# of Gears,4287.0,6.052018,3.397571,1.000000,1.000000,8.000000,8.000000,10.000000
Transmission Overdrive Code,4287.0,1.844180,0.362727,1.000000,2.000000,2.000000,2.000000,2.000000
Equivalent Test Weight (lbs.),4287.0,4818.783532,985.818195,2750.000000,4000.000000,4750.000000,5500.000000,9000.000000
Axle Ratio,4287.0,3.784444,1.718661,0.000000,3.200000,3.450000,3.900000,9.990000
N/V Ratio,4287.0,57.373221,142.381594,0.000000,23.300000,25.700000,30.100000,999.000000
Shift Indicator Light Use Cd,4287.0,1.073478,0.475693,1.000000,1.000000,1.000000,1.000000,5.000000
ADFE Total Road Load HP,212.0,17.188208,3.136153,11.000000,14.725000,17.600000,19.100000,26.100000
ADFE Equiv. Test Weight (lbs.),212.0,4883.254717,706.324859,3125.000000,4250.000000,5000.000000,5500.000000,6000.000000
ADFE N/V Ratio,212.0,25.790094,3.405633,20.000000,23.300000,25.500000,28.100000,43.900000
Test Procedure Cd,4287.0,36.230231,35.642649,2.000000,3.000000,21.000000,81.000000,95.000000
Test Fuel Type Cd,4287.0,57.800093,10.737065,19.000000,61.000000,61.000000,61.000000,62.000000
THC (g/mi),3329.0,0.019636,0.041647,0.000000,0.002846,0.009841,0.019335,0.481797
CO (g/mi),3403.0,0.310576,0.498661,0.000000,0.067575,0.168824,0.363587,10.352100
CO2 (g/mi),3563.0,304.229007,127.582740,0.000000,215.814565,277.000000,376.662400,1093.643465
NOx (g/mi),3402.0,0.008894,0.011352,0.000000,0.001811,0.004700,0.012001,0.105800
PM (g/mi),389.0,385.604847,1927.927659,0.000000,0.000230,0.000543,0.001100,10000.000000
CH4 (g/mi),3165.0,0.005268,0.007251,0.000000,0.001347,0.002985,0.006489,0.068720
N2O (g/mi),2224.0,0.002533,0.007574,0.000000,0.000070,0.000445,0.001201,0.048982
RND_ADJ_FE,4066.0,64.962322,456.941030,0.000000,24.300000,32.900000,43.700000,10000.000000
FE Bag 1,1864.0,24.256323,24.097875,7.900000,17.778365,22.859589,28.600000,999.000000
FE Bag 2,1864.0,32.458864,29.577159,8.600000,21.600000,27.444693,34.299769,999.000000
FE Bag 3,1453.0,30.363268,26.838005,11.200000,23.340000,29.097803,34.800000,999.000000
FE Bag 4,388.0,45.315583,32.448996,0.000000,26.284134,34.475000,47.805953,220.500000
DT-Inertia Work Ratio Rating,3592.0,0.686646,3.127829,-16.890000,-0.628020,0.520000,1.784623,23.031000
DT-Absolute Speed Change Ratg,3592.0,0.511288,2.949315,-50.263000,-0.465539,0.330000,1.280075,17.743000
DT-Energy Economy Rating,3592.0,-0.181234,0.813975,-5.440000,-0.570000,-0.156925,0.161136,9.390000
Target Coef A (lbf),4287.0,40.269675,12.293289,16.140000,31.345000,38.860000,46.545000,93.000000
Target Coef B (lbf/mph),4287.0,0.245435,0.282932,-0.712000,0.056150,0.226100,0.409800,1.750000
Target Coef C (lbf/mph**2),4287.0,0.024718,0.006881,0.011599,0.019710,0.023480,0.028540,0.054180
Set Coef A (lbf),4287.0,6.205490,12.617524,-52.800000,-1.262000,8.250000,14.300000,99.999000
Set Coef B (lbf/mph),4287.0,0.109309,0.380594,-1.267800,-0.020420,0.094100,0.227400,9.999990
Set Coef C (lbf/mph**2),4287.0,0.033204,0.304741,-0.090640,0.018795,0.022773,0.027207,9.999999
Averaging Weighting Factor,75.0,0.500000,0.000000,0.500000,0.500000,0.500000,0.500000,0.500000

**--- 3. Análisis de configuraciones y ensayos múltiples---**

**Configuraciones únicas**

In [55]:
columnas_configuracion = ['Veh Mfr Code', 'Test Vehicle ID', 'Test Veh Configuration #']

In [56]:
config_unicas = df.drop_duplicates(subset=columnas_configuracion)
print(f"Total de registros totales: {len(df)}")
print(f"Total de configuraciones únicas de vehículos: {len(config_unicas)}")
print(f"Registros repetidos por ensayos múltiples: {len(df) - len(config_unicas)}")

Total de registros totales: 4287
Total de configuraciones únicas de vehículos: 1448
Registros repetidos por ensayos múltiples: 2839